version: "3.2"

services: 
    backend:
        build:
            context: ./dockerfiles/dev
        volumes:
            - .:/server
        command: sh -c 'cd /server && yarn && yarn start'
        environment: 
            JWT_SECRET:
            MONGO_URI:
        ports:
            - 10000:10000
            - 10001:10001
            